services:

  backend:
    container_name: greprag-backend

    build:
      context: .
      dockerfile: backend/Dockerfile

    image: greprag-backend

    ports:
      - "8000:8000"

    env_file:
      - .env

    environment:
      TZ: Asia/Kolkata

    volumes:
      - ./documents:/app/documents
      - ./memory:/app/memory
      - ./logs:/app/logs

    restart: unless-stopped


  frontend:
    container_name: greprag-frontend

    build:
      context: .
      dockerfile: frontend/Dockerfile

    image: greprag-frontend

    ports:
      - "8501:8501"

    environment:
      API_URL: http://backend:8000
      TZ: Asia/Kolkata

    depends_on:
      - backend

    restart: unless-stopped